#ifndef GEOSECURECOMMONS_GLOBAL_H
#define GEOSECURECOMMONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOSECURECOMMONS_LIBRARY)
#  define GEOSECURECOMMONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GEOSECURECOMMONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOSECURECOMMONS_GLOBAL_H
